name: mcp23017

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run chipmode tests
      run: cargo test --features chipmode
    - name: Run portmode tests
      run: cargo test --features portmode
    - name: Run pinmode tests
      run: cargo test --features pinmode
